CUSTOM_SKILL_PATTERNS = {
    'Python': ['python', 'py'],
    'Java': ['java'],
    'JavaScript': ['javascript', 'js', 'es6', 'es7', 'es8', 'ecmascript'],
    'TypeScript': ['typescript', 'ts'],
    'C++': ['c++', 'cpp'],
    'C#': ['c#', 'c-sharp', 'c sharp', '.net', 'dotnet'],
    'C': ['c'],
    'PHP': ['php'],
    'SQL': ['sql', 'structured query language'],
    'Ruby': ['ruby'],
    'Go': ['go', 'golang'],
    'Rust': ['rust'],
    'Swift': ['swift'],
    'Kotlin': ['kotlin'],
    'R': ['r', 'r language'],
    'Scala': ['scala'],
    'Bash': ['bash', 'shell script', 'shell scripting', 'sh'],
    'PowerShell': ['powershell', 'ps1'],
    'Perl': ['perl'],
    'Lua': ['lua'],
    'Haskell': ['haskell'],
    'MATLAB': ['matlab'],
    'Groovy': ['groovy'],
    'Objective-C': ['objective-c', 'obj-c'],
    'Dart': ['dart'],
    'Artificial Intelligence': ['ai', 'artificial intelligence'],
    'Machine Learning': ['machine learning', 'ml'],
    'Deep Learning': ['deep learning', 'dl', 'neural networks', 'neural nets'],
    'Natural Language Processing': ['nlp', 'natural language processing'],
    'Computer Vision': ['computer vision', 'cv', 'image processing', 'image recognition'],
    'Data Analysis': ['data analysis', 'data analytics', 'data analyst'],
    'Data Science': ['data science', 'data scientist'],
    'Data Mining': ['data mining'],
    'Data Visualization': ['data visualization', 'dataviz'],
    'Statistical Analysis': ['statistics', 'statistical analysis', 'statistical modeling'],
    'Generative AI': ['generative ai', 'genai', 'large language models', 'llm', 'llms'],
    'Reinforcement Learning': ['reinforcement learning', 'rl'],
    'Predictive Modeling': ['predictive modeling', 'predictive models', 'forecasting'],
    'Big Data': ['big data'],
    'TensorFlow': ['tensorflow', 'tf'],
    'PyTorch': ['pytorch', 'torch'],
    'Keras': ['keras'],
    'Scikit-Learn': ['scikit-learn', 'sklearn'],
    'Pandas': ['pandas'],
    'NumPy': ['numpy'],
    'SciPy': ['scipy'],
    'Matplotlib': ['matplotlib'],
    'Seaborn': ['seaborn'],
    'Hugging Face': ['hugging face', 'huggingface'],
    'spaCy': ['spacy'],
    'NLTK': ['nltk'],
    'OpenCV': ['opencv'],
    'Jupyter': ['jupyter', 'jupyter notebooks', 'ipython'],
    'HTML': ['html', 'html5'],
    'CSS': ['css', 'css3', 'cascading style sheets'],
    'Sass': ['sass', 'scss'],
    'LESS': ['less'],
    'React': ['react', 'react.js', 'reactjs'],
    'Angular': ['angular', 'angular.js', 'angularjs'],
    'Vue.js': ['vue', 'vue.js', 'vuejs'],
    'Svelte': ['svelte'],
    'Redux': ['redux'],
    'jQuery': ['jquery'],
    'Bootstrap': ['bootstrap'],
    'Tailwind CSS': ['tailwind css', 'tailwind'],
    'Webpack': ['webpack'],
    'Vite': ['vite'],
    'Next.js': ['next.js', 'nextjs'],
    'Gatsby': ['gatsby'],
    'Node.js': ['node.js', 'nodejs', 'node'],
    'Express.js': ['express.js', 'expressjs', 'express'],
    'Django': ['django'],
    'Flask': ['flask'],
    'FastAPI': ['fastapi'],
    'Spring': ['spring', 'spring framework'],
    'Spring Boot': ['spring boot'],
    'Ruby on Rails': ['ruby on rails', 'rails'],
    'ASP.NET': ['asp.net', 'asp'],
    'Laravel': ['laravel'],
    'Symfony': ['symfony'],
    'REST': ['rest', 'restful apis', 'rest api'],
    'GraphQL': ['graphql'],
    'gRPC': ['grpc'],
    'JSON': ['json'],
    'XML': ['xml'],
    'WebSockets': ['websockets', 'websocket'],
    'PostgreSQL': ['postgresql', 'postgres'],
    'MySQL': ['mysql'],
    'Microsoft SQL Server': ['ms sql', 'mssql', 'sql server'],
    'Oracle Database': ['oracle db', 'oracle'],
    'MariaDB': ['mariadb'],
    'SQLite': ['sqlite'],
    'MongoDB': ['mongodb', 'mongo'],
    'Redis': ['redis'],
    'Cassandra': ['cassandra'],
    'Elasticsearch': ['elasticsearch', 'elastic'],
    'DynamoDB': ['dynamodb'], 
    'Firebase': ['firebase'], 
    'Apache Spark': ['spark', 'apache spark', 'pyspark'],
    'Apache Hadoop': ['hadoop', 'hdfs'],
    'Apache Kafka': ['kafka', 'apache kafka'],
    'Apache Flink': ['flink', 'apache flink'],
    'Apache Airflow': ['airflow', 'apache airflow'],
    'Data Warehousing': ['data warehouse', 'data warehousing'],
    'ETL': ['etl', 'extract transform load'],
    'DBT': ['dbt', 'data build tool'],
        'DevOps': ['devops'],
    'SRE': ['sre', 'site reliability engineering'],
    'CI/CD': ['ci/cd', 'ci-cd', 'continuous integration', 'continuous delivery', 'continuous deployment'],
    'Git': ['git', 'github', 'gitlab', 'bitbucket', 'version control'],
    'Docker': ['docker'],
    'Kubernetes': ['kubernetes', 'k8s'],
    'Helm': ['helm'],
    'Podman': ['podman'],
    'Containerd': ['containerd'],
    'Terraform': ['terraform'],
    'Ansible': ['ansible'],
    'Puppet': ['puppet'],
    'Chef': ['chef'],
    'Pulumi': ['pulumi'],
    'CloudFormation': ['cloudformation', 'cfn'], 
    'Jenkins': ['jenkins'],
    'GitHub Actions': ['github actions'],
    'GitLab CI': ['gitlab ci'],
    'CircleCI': ['circleci'],
    'Travis CI': ['travis ci'],
    'Argo CD': ['argo cd', 'argocd'],
    'Prometheus': ['prometheus'],
    'Grafana': ['grafana'],
    'Datadog': ['datadog'],
    'Splunk': ['splunk'],
    'New Relic': ['new relic'],
    'ELK Stack': ['elk', 'elk stack', 'elasticsearch logstash kibana'],
    'Logging': ['logging', 'log management'],
        'Cloud Computing': ['cloud', 'cloud computing'],
    'AWS': ['aws', 'amazon web services'],
    'EC2': ['ec2'],
    'S3': ['s3', 'simple storage service'],
    'Lambda': ['lambda', 'aws lambda'],
    'RDS': ['rds', 'relational database service'],
    'VPC': ['vpc', 'virtual private cloud'],
    'IAM': ['iam', 'identity and access management'],
    'EKS': ['eks', 'elastic kubernetes service'],
    'ECS': ['ecs', 'elastic container service'],
    'Sagemaker': ['sagemaker'],
    'CloudWatch': ['cloudwatch'],
    'SQS': ['sqs', 'simple queue service'],
    'SNS': ['sns', 'simple notification service'],
    'Route 53': ['route 53', 'route53'],
    'Azure': ['azure', 'microsoft azure'],
    'Azure Virtual Machines': ['azure vm', 'azure virtual machines'],
    'Azure Blob Storage': ['azure blob storage', 'blob storage'],
    'Azure Functions': ['azure functions'],
    'Azure SQL Database': ['azure sql'],
    'Azure Cosmos DB': ['cosmos db'],
    'Azure Kubernetes Service (AKS)': ['aks', 'azure kubernetes service'],
    'Azure DevOps': ['azure devops'],
    'Google Cloud (GCP)': ['gcp', 'google cloud', 'google cloud platform'],
    'Compute Engine': ['gce', 'compute engine'],
    'Cloud Storage': ['gcs', 'google cloud storage'],
    'Cloud Functions': ['gcf', 'google cloud functions'],
    'Cloud SQL': ['cloud sql'],
    'BigQuery': ['bigquery'],
    'Google Kubernetes Engine (GKE)': ['gke', 'google kubernetes engine'],
    'Vertex AI': ['vertex ai'],
    'Cybersecurity': ['cybersecurity', 'cyber security', 'information security', 'infosec'],
    'DevSecOps': ['devsecops'],
    'Penetration Testing': ['penetration testing', 'pentesting', 'ethical hacking'],
    'Vulnerability Assessment': ['vulnerability assessment', 'vulnerability scanning', 'vulnerability detection'],
    'Incident Response': ['incident response', 'ir'],
    'Threat Analysis': ['threat analysis', 'threat intelligence', 'threat hunting'],
    'SIEM': ['siem', 'security information and event management'],
    'Cryptography': ['cryptography', 'encryption'],
    'Network Security': ['network security'],
    'Application Security': ['application security', 'appsec'],
    'Nmap': ['nmap'],
    'Wireshark': ['wireshark'],
    'Metasploit': ['metasploit'],
    'Burp Suite': ['burp suite', 'burpsuite'],
    'OWASP ZAP': ['owasp zap', 'zap proxy'],
    'OWASP': ['owasp', 'owasp top 10'],
    'NIST': ['nist'],
    'ISO 27001': ['iso 27001', 'iso27001'],
    'SOC2': ['soc2', 'soc 2'],
    'Mobile Development': ['mobile development', 'mobile app development'],
    'iOS Development': ['ios', 'ios development'],
    'Android Development': ['android', 'android development'],
    'React Native': ['react native'],
    'Flutter': ['flutter'],
    'Xamarin': ['xamarin'],
    'QA': ['qa', 'quality assurance'],
    'Software Testing': ['software testing'],
    'Manual Testing': ['manual testing'],
    'Automated Testing': ['automated testing', 'test automation'],
    'Unit Testing': ['unit testing', 'unit tests'],
    'Integration Testing': ['integration testing'],
    'End-to-End Testing': ['e2e testing', 'end-to-end testing'],
    'TDD': ['tdd', 'test-driven development'],
    'BDD': ['bdd', 'behavior-driven development'],
    'Selenium': ['selenium', 'selenium webdriver'],
    'Cypress': ['cypress'],
    'Playwright': ['playwright'],
    'Jest': ['jest'],
    'PyTest': ['pytest'],
    'JUnit': ['junit'],
    'TestNG': ['testng'],
    'Postman': ['postman'],
    'Project Management': ['project management', 'pm'],
    'Product Management': ['product management'],
    'Agile': ['agile', 'agile methodologies'],
    'Scrum': ['scrum'],
    'Kanban': ['kanban'],
    'Lean': ['lean'],
    'Waterfall': ['waterfall'],
    'PRINCE2': ['prince2'],
    'Stakeholder Management': ['stakeholder management'],
    'Roadmap Planning': ['roadmap planning', 'product roadmap'],
    'Business Analysis': ['business analysis', 'business analyst'],
    'Jira': ['jira'],
    'Confluence': ['confluence'],
    'Trello': ['trello'],
    'Asana': ['asana'],
    'Monday.com': ['monday.com', 'monday'],
    'Microsoft Project': ['ms project', 'microsoft project'],
    'Excel': ['excel', 'spreadsheets', 'ms excel'],
    'Google Sheets': ['google sheets'],
    'Microsoft Office': ['office', 'ms office', 'microsoft office', 'word', 'powerpoint', 'outlook'],
    'Tableau': ['tableau'],
    'Power BI': ['power bi', 'powerbi'],
        'UI/UX Design': ['ui/ux', 'ui-ux', 'ui design', 'ux design', 'user experience', 'user interface'],
    'User Research': ['user research'],
    'Wireframing': ['wireframing', 'wireframes'],
    'Prototyping': ['prototyping', 'prototypes'],
    'Figma': ['figma'],
    'Sketch': ['sketch'],
    'Adobe XD': ['adobe xd', 'xd'],
    'Adobe Photoshop': ['photoshop', 'adobe photoshop'],
    'Adobe Illustrator': ['illustrator', 'adobe illustrator'],
    'InVision': ['invision'],
    'Design Systems': ['design systems'],
    'System Administration': ['sysadmin', 'system administration', 'system administrator'],
    'Linux': ['linux', 'ubuntu', 'centos', 'debian', 'red hat', 'rhel'],
    'Windows Server': ['windows server'],
    'Active Directory': ['active directory', 'ad'],
    'Networking': ['networking'],
    'TCP/IP': ['tcp/ip'],
    'DNS': ['dns'],
    'DHCP': ['dhcp'],
    'Firewalls': ['firewalls', 'firewall configuration'],
    'Virtualization': ['virtualization'],
    'VMware': ['vmware', 'vsphere'],
    'Hyper-V': ['hyper-v'],
    'Game Development': ['game development', 'game dev'],
    'Unity': ['unity', 'unity3d'],
    'Unreal Engine': ['unreal engine', 'ue4', 'ue5'],
    '3D Modeling': ['3d modeling'],
    'Blender': ['blender'],
    'Maya': ['autodesk maya', 'maya'],
    'Communication': ['communication', 'communicating', 'written communication', 'verbal communication'],
    'Teamwork': ['teamwork', 'collaboration', 'collaborative'],
    'Problem Solving': ['problem solving', 'troubleshooting', 'problem-solving', 'finding resolutions'],
    'Leadership': ['leadership', 'team lead', 'managing', 'leading a team', 'management'],
    'Time Management': ['time management', 'prioritization'],
    'Organization': ['organization', 'organizational skills'],
    'Adaptability': ['adaptability', 'flexible', 'adaptable'],
    'Creativity': ['creativity', 'creative thinking'],
    'Critical Thinking': ['critical thinking'],
    'Mentorship': ['mentoring', 'mentorship', 'coaching'],
    'Client Relations': ['client relations', 'customer-facing', 'client management'],
    'Accountability': ['accountability', 'ownership'],
    'Transparency': ['transparency'],
}