# Generated by Django 5.2.7 on 2025-10-25 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_profile_job_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='github_username',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
