# Generated by Django 5.2.7 on 2025-10-25 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_profile_linkedin_url_profile_website_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='additional_website_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
